# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/ssj" # the subpath of your site, e.g. /blog/

twitter_username:
github_username:

# Build settings
markdown: kramdown
