# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/ssj" # the subpath of your site, e.g. /blog/
url: "https://SSJcoders.github.io"
twitter_username:
github_username:

# Build settings
markdown: kramdown
